### ISSUE TITLE
License badge is HTTP

### ISSUE THREAD

**Issue by paulboocock** [snowplow-devops/terraform-module-template#1]
The License badge on any usage of this template doesn't load on the Terraform Registry as its `http`, and the image needs to be `https` to load. See https://registry.terraform.io/modules/snowplow-devops/postgres-loader-kinesis-ec2/aws/0.1.0 for an example.

<img width="693" alt="Screenshot 2021-07-12 at 16 38 57" src="https://user-images.githubusercontent.com/8820009/125316403-01056c00-e330-11eb-8891-295f3593b3ac.png">

**Comment by jbeemster** [comment]
Fixed!
